name: Build ARIana (Linux, Nuitka)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - "**.py"
      - "Patients/**"
      - "ARIana_logo.png"
      - ".github/workflows/build-linux-nuitka.yml"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo layout
        run: |
          pwd
          ls -la
          echo "Top-level files:"
          find . -maxdepth 1 -type f -print
          echo "Top-level dirs:"
          find . -maxdepth 1 -type d -print

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # no pip cache

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-tk tk tcl \
            patchelf build-essential

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install "nuitka>=2.4" pillow numpy scipy pyserial matplotlib

      - name: Verify tkinter import
        run: |
          python - << 'PY'
          import tkinter as tk
          print("tkinter OK")
          PY

      - name: Build (Linux, Nuitka)
        shell: bash
        run: |
          set -eo pipefail

          if [[ ! -f "ARIana.py" ]]; then
            echo "ERROR: ARIana.py not found in $(pwd)"
            exit 1
          fi

          NUITKA_FLAGS=(
            --standalone
            --enable-plugin=tk-inter
            --include-module=tkinter
            --include-module=PIL
            --include-module=matplotlib
            --include-module=numpy
            --include-module=scipy
            --include-module=serial
            --output-dir=build_linux
          )

          if [[ -d "Patients" ]]; then
            NUITKA_FLAGS+=( --include-data-dir=Patients=Patients )
          else
            echo "NOTE: Patients/ directory not found; skipping data include."
          fi

          if [[ -f "ARIana_logo.png" ]]; then
            NUITKA_FLAGS+=( --include-data-file=ARIana_logo.png=ARIana_logo.png )
          else
            echo "NOTE: ARIana_logo.png not found; skipping data file include."
          fi

          echo "Running Nuitka with flags:"
          printf '  %q\n' "${NUITKA_FLAGS[@]}"

          python3 -m nuitka "${NUITKA_FLAGS[@]}" ARIana.py

      - name: Package artifact (.tar.gz)
        shell: bash
        run: |
          set -eo pipefail
          if [[ ! -d "build_linux" ]]; then
            echo "ERROR: build_linux/ not found; build likely failed."
            exit 1
          fi
          tar -czvf ARIana-linux.tar.gz build_linux/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ARIana-linux
          path: ARIana-linux.tar.gz
          if-no-files-found: error
