- name: Verify imports (fail fast)
  shell: pwsh
  run: |
    $missing = @()
    foreach ($m in @("PIL", "serial", "numpy", "scipy", "matplotlib", "tkinter")) {
      try {
        python -c "import $m" 2>$null
      } catch {
        $missing += "$m : $($_.Exception.Message)"
      }
    }
    if ($missing.Count -gt 0) {
      Write-Host "Missing/failed imports:"
      $missing | ForEach-Object { Write-Host $_ }
      exit 1
    }
    Write-Host "All required imports available."
