name: Build ARIana (Linux, Nuitka)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - "**.py"
      - "**/Patients/**"
      - "**/ARIana_logo.png"
      - ".github/workflows/build-linux-nuitka.yml"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo layout (debug)
        run: |
          pwd
          ls -la
          echo "---- files ----"
          git ls-files | sed 's/^/  /'
          echo "--------------"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # no pip cache

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk tk tcl patchelf build-essential

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install "nuitka>=2.4" pillow numpy scipy pyserial matplotlib

      - name: Locate project + verify tkinter
        id: locate
        shell: bash
        run: |
          set -eo pipefail

          APP_MAIN="$(git ls-files | grep -E '(^|.*/)(ARIana\.py)$' | head -n1 || true)"
          if [[ -z "$APP_MAIN" ]]; then
            echo "ERROR: Could not find ARIana.py anywhere in repo."
            exit 1
          fi
          APP_DIR="$(dirname "$APP_MAIN")"
          [[ "$APP_DIR" == "." ]] && APP_DIR="$GITHUB_WORKSPACE"

          echo "Found ARIana.py at: $APP_MAIN"
          echo "Using APP_DIR: $APP_DIR"

          if [[ -d "$APP_DIR/Patients" ]]; then
            DATA_DIR="$APP_DIR/Patients"
          elif [[ -d "$GITHUB_WORKSPACE/Patients" ]]; then
            DATA_DIR="$GITHUB_WORKSPACE/Patients"
          else
            DATA_DIR=""
          fi
          echo "DATA_DIR=$DATA_DIR" >> $GITHUB_OUTPUT

          if [[ -f "$APP_DIR/ARIana_logo.png" ]]; then
            ICON_PATH="$APP_DIR/ARIana_logo.png"
          elif [[ -f "$GITHUB_WORKSPACE/ARIana_logo.png" ]]; then
            ICON_PATH="$GITHUB_WORKSPACE/ARIana_logo.png"
          else
            ICON_PATH=""
          fi
          echo "ICON_PATH=$ICON_PATH" >> $GITHUB_OUTPUT

          python - << 'PY'
          import tkinter as tk
          print("tkinter OK")
          PY

          echo "APP_MAIN=$APP_MAIN" >> $GITHUB_OUTPUT
          echo "APP_DIR=$APP_DIR" >> $GITHUB_OUTPUT

      - name: Build (Linux, Nuitka)
        shell: bash
        run: |
          set -eo pipefail
          APP_MAIN="${{ steps.locate.outputs.APP_MAIN }}"
          APP_DIR="${{ steps.locate.outputs.APP_DIR }}"
          DATA_DIR="${{ steps.locate.outputs.DATA_DIR }}"
          ICON_PATH="${{ steps.locate.outputs.ICON_PATH }}"

          echo "Building from: $APP_DIR"
          cd "$APP_DIR"

          NUITKA_FLAGS=(
            --standalone
            --enable-plugin=tk-inter
            --include-module=tkinter
            --include-module=PIL
            --include-module=matplotlib
            --include-module=numpy
            --include-module=scipy
            --include-module=serial
            --output-dir=build_linux
          )

          if [[ -n "$DATA_DIR" ]]; then
            NUITKA_FLAGS+=( "--include-data-dir=${DATA_DIR}=Patients" )
          else
            echo "NOTE: Patients/ not found; skipping include."
          fi

          if [[ -n "$ICON_PATH" ]]; then
            NUITKA_FLAGS+=( "--include-data-file=${ICON_PATH}=ARIana_logo.png" )
          else
            echo "NOTE: ARIana_logo.png not found; skipping include."
          fi

          echo "Nuitka flags:"
          printf '  %q\n' "${NUITKA_FLAGS[@]}"

          python3 -m nuitka "${NUITKA_FLAGS[@]}" "$(basename "$APP_MAIN")"

      - name: Package artifact (.tar.gz)
        shell: bash
        run: |
          set -eo pipefail
          APP_DIR="${{ steps.locate.outputs.APP_DIR }}"
          cd "$APP_DIR"
          if [[ ! -d "build_linux" ]]; then
            echo "ERROR: build_linux/ not found; build likely failed."
            ls -la
            exit 1
          fi
          tar -czvf ARIana-linux.tar.gz build_linux/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ARIana-linux
          path: ${{ steps.locate.outputs.APP_DIR }}/ARIana-linux.tar.gz
          if-no-files-found: error
