name: Build Mac App (Nuitka)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - "**.py"
      - "Patients/**"
      - "ARIana_logo.png"
      - ".github/workflows/build-macos-nuitka.yml"

jobs:
  build-macos:
    runs-on: macos-latest
    env:
      TK_SILENCE_DEPRECATION: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo layout
        run: |
          pwd
          ls -la
          echo "Top-level files:"
          find . -maxdepth 1 -type f -print
          echo "Top-level dirs:"
          find . -maxdepth 1 -type d -print

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"   # no pip cache (avoids requirements.txt errors)

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "nuitka>=2.4" pillow numpy scipy pyserial matplotlib

      - name: Verify tkinter availability
        run: |
          python - << 'PY'
          import tkinter as tk
          print("tkinter OK")
          PY

      - name: Build app bundle with Nuitka
        shell: bash
        run: |
          # Be strict on errors, but don't die on unset vars
          set -eo pipefail

          if [[ ! -f "ARIana.py" ]]; then
            echo "ERROR: ARIana.py not found in $(pwd)"
            exit 1
          fi

          # Build flags dynamically so missing assets don't cause hard failure
          NUITKA_FLAGS=(
            --standalone
            --enable-plugin=tk-inter
            --include-module=tkinter
            --include-module=PIL
            --include-module=matplotlib
            --include-module=numpy
            --include-module=scipy
            --include-module=serial
            --macos-create-app-bundle
            --macos-app-name=ARIana
            --output-dir=build_macos
            --macos-sign-identity=-
          )

          if [[ -d "Patients" ]]; then
            NUITKA_FLAGS+=( --include-data-dir=Patients=Patients )
          else
            echo "NOTE: Patients/ directory not found; skipping data include."
          fi

          if [[ -f "ARIana_logo.png" ]]; then
            NUITKA_FLAGS+=( --include-data-file=ARIana_logo.png=ARIana_logo.png )
            NUITKA_FLAGS+=( --macos-app-icon=ARIana_logo.png )
          else
            echo "NOTE: ARIana_logo.png not found; skipping icon and data file include."
          fi

          echo "Running Nuitka with flags:"
          printf '  %q\n' "${NUITKA_FLAGS[@]}"

          python3 -m nuitka "${NUITKA_FLAGS[@]}" ARIana.py

      - name: Create DMG
        shell: bash
        run: |
          set -eo pipefail
          APP_PATH="build_macos/ARIana.app"
          if [[ ! -d "$APP_PATH" ]]; then
            echo "ERROR: Expected app bundle not found at $APP_PATH"
            echo "Contents of build_macos:"
            ls -la build_macos || true
            exit 1
          fi
          hdiutil create -volname "ARIana" -srcfolder "$APP_PATH" -ov -format UDZO ARIana.dmg
          ls -lh ARIana.dmg

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: ARIana-macOS-DMG
          path: ARIana.dmg
          if-no-files-found: error
