name: Build Windows App (Nuitka)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          if (Test-Path "requirements.txt") {
            pip install -r requirements.txt --only-binary=:all:
          }
          # Ensure runtime deps even if not in requirements.txt
          pip install --upgrade pillow pyserial numpy scipy matplotlib --only-binary=:all:

      - name: Verify imports (fail fast)
        run: |
          python - << 'PY'
          import sys
          missing = []
          for m in ("PIL", "serial", "numpy", "scipy", "matplotlib", "tkinter"):
              try:
                  __import__(m)
              except Exception as e:
                  missing.append((m, str(e)))
          if missing:
              for m, err in missing:
                  print(f"Missing/failed import: {m} -> {err}")
              sys.exit(1)
          print("All required imports available.")
          PY

      - name: Build with Nuitka
        run: |
          $flags = @(
            '--standalone',
            '--windows-disable-console',
            '--include-data-dir="Source Code/Patients=Patients"',
            '--include-data-file="Source Code/ARIana_logo.png=ARIana_logo.png"',
            '--include-module=tkinter',
            '--include-module=PIL',
            '--include-module=matplotlib',
            '--include-module=numpy',
            '--include-module=scipy',
            '--include-module=serial',
            '--enable-plugin=tk-inter',
            '--windows-icon-from-ico="Source Code/ARIana.ico"',
            '--output-dir=build_windows'
          )

          python -m nuitka $flags "Source Code/ARIana.py"

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: ARIana-Windows
          path: build_windows/**
