name: Build Windows App (Nuitka)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install --upgrade pip wheel setuptools
          if (Test-Path "requirements.txt") {
            pip install -r requirements.txt --only-binary=:all:
          }
          pip install --upgrade nuitka ordered-set zstandard
          pip install --upgrade pillow pyserial numpy scipy matplotlib --only-binary=:all:

      - name: Verify imports (fail fast)
        shell: pwsh
        run: |
          $modules = @("PIL","serial","numpy","scipy","matplotlib","tkinter")
          $missing = @()
          foreach ($m in $modules) {
            $cmd = "import $m"
            $p = Start-Process -FilePath python -ArgumentList "-c `"$cmd`"" -NoNewWindow -PassThru -Wait
            if ($p.ExitCode -ne 0) { $missing += $m }
          }
          if ($missing.Count -gt 0) {
            Write-Host "Missing/failed imports: $($missing -join ', ')"
            exit 1
          }
          Write-Host "All required imports available."

      - name: Build with Nuitka (console forced for debug)
        shell: pwsh
        env:
          NUITKA_ASSUME_YES_FOR_DOWNLOADS: "1"
        run: |
          $flags = @(
            '--standalone',
            '--windows-console-mode=force',
            "--include-data-dir=Source Code/Patients=Patients",
            "--include-data-file=Source Code/ARIana_logo.png=ARIana_logo.png",
            '--include-module=tkinter',
            '--include-module=PIL',
            '--include-module=matplotlib',
            '--include-module=numpy',
            '--include-module=scipy',
            '--include-module=serial',
            '--enable-plugin=tk-inter',
            '--enable-plugin=matplotlib',
            '--enable-plugin=numpy',
            '--output-dir=build_windows',
            '--assume-yes-for-downloads'


          )
          if (Test-Path "Source Code/ARIana_logo.ico") {
            $flags += "--windows-icon-from-ico=Source Code/ARIana_logo.ico"
          }
          Write-Host "Running: python -m nuitka $($flags -join ' ') 'Source Code/ARIana.py'"
          python -m nuitka $flags "Source Code/ARIana.py"

      - name: Upload build artifact (.dist only)
        uses: actions/upload-artifact@v4
        with:
          name: ARIana-Windows-standalone
          path: build_windows/ARIana.dist/**
          if-no-files-found: error
